# Generated by Django 5.1.5 on 2025-06-02 14:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_type', models.CharField(choices=[('', 'Select'), ('policy_issue', 'Policy Issue'), ('payment_problem', 'Payment Problem'), ('service_delay', 'Service Delay'), ('document_error', 'Document Error'), ('other', 'Other')], default='', help_text='Select status', max_length=20)),
                ('complaint', models.CharField(max_length=30)),
                ('comp_date', models.DateField()),
                ('action', models.CharField(choices=[('', 'Select'), ('investigation', 'Investigation Initiated'), ('resolved', 'Resolved'), ('pending', 'Pending Further Review'), ('escalated', 'Escalated to Higher Authority')], default='', help_text='Select status', max_length=30, null='True')),
                ('act_date', models.DateField(null=True)),
                ('comp_status', models.CharField(choices=[('', 'Select'), ('received', 'received'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='', help_text='Select status', max_length=30, null='True')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.customerregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email_id', models.EmailField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10, null=True)),
                ('qualification', models.CharField(choices=[('', 'Select'), ('High School', 'High School'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate')], default='', help_text="Select the user's highest qualification", max_length=30, null=True)),
                ('occupation', models.CharField(max_length=20, null=True)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('physical_status', models.CharField(choices=[('', 'Select'), ('normal', 'Normal'), ('disabled', 'Disabled'), ('partially_disabled', 'Partially Disabled'), ('amputee', 'Amputee'), ('other', 'Other')], default='', help_text='Select status', max_length=30, null=True)),
                ('health_condition', models.CharField(choices=[('', 'Select'), ('healthy', 'Healthy'), ('chronic_illness', 'Chronic Illness'), ('heart_disease', 'Heart Disease'), ('diabetic', 'Diabetic'), ('cancer_history', 'History of Cancer'), ('other', 'Other')], default='', help_text='Select status', max_length=30, null=True)),
                ('business_status', models.CharField(choices=[('', 'Select'), ('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('student', 'Student')], default='', help_text='Select status', max_length=30, null=True)),
                ('identification_mark', models.CharField(max_length=30, null=True)),
                ('identity_proof', models.ImageField(help_text='Upload Identity Proof(Aadhaar, Passport, etc)', null=True, upload_to='identity_proof/')),
                ('nominee_name', models.CharField(max_length=25, null=True)),
                ('nom_rel', models.CharField(max_length=20, null=True)),
                ('payment_mode', models.CharField(max_length=20, null=True)),
                ('credit_card_no', models.BigIntegerField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='customer_photos/')),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('', 'Select'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='inactive', help_text='Select status', max_length=30, null=True)),
                ('distid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.district')),
                ('stateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.state')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPolicy',
            fields=[
                ('cpol_id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_date', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('premium_amt', models.FloatField(null=True)),
                ('policy_status', models.CharField(choices=[('', 'Select'), ('approved', 'approved'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('renewed', 'Renewed')], default='pending', help_text='Select status', max_length=30)),
                ('agent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.agentregistration')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.customerregistration')),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.policies')),
                ('premium_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.premium_mode')),
            ],
        ),
        migrations.CreateModel(
            name='CustPolDocs',
            fields=[
                ('poldoc_id', models.AutoField(primary_key=True, serialize=False)),
                ('documents', models.FileField(blank=True, help_text='Upload documents', null=True, upload_to='customer_documents/')),
                ('doc_status', models.CharField(choices=[('', 'Select'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('pending_review', 'Pending Review')], default='pending_review', help_text='Select status', max_length=30)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.customerregistration')),
                ('docu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.policy_documents')),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.policies')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumSchedules',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('premium_no', models.CharField(max_length=20)),
                ('premium_date', models.DateField()),
                ('due_date', models.DateField()),
                ('pay_status', models.CharField(choices=[('', 'Select'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('overdue', 'Overdue'), ('partial', 'Partial Payment')], default='', help_text='Select status', max_length=30)),
                ('cpol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customerpolicy')),
                ('pre_mode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.premium_mode')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumPayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_date', models.DateField()),
                ('premium_amt', models.FloatField()),
                ('due_amt', models.FloatField()),
                ('total_amt', models.FloatField()),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.premiumschedules')),
            ],
        ),
    ]
