# Generated by Django 5.1.5 on 2025-06-04 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpolicy',
            name='agent_id',
        ),
    ]
