# Generated by Django 5.1.5 on 2025-06-04 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('users', '0002_remove_customerpolicy_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpolicy',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.agentregistration'),
        ),
    ]
