# Generated by Django 5.1.5 on 2025-06-04 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('users', '0003_customerpolicy_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpolicy',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerpolicy', to='login.agentregistration'),
        ),
    ]
