# Generated by Django 5.1.5 on 2025-06-02 14:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRegistration',
            fields=[
                ('Agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('Agent_Fname', models.CharField(max_length=25)),
                ('Agent_Lname', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=15)),
                ('Address_line1', models.CharField(max_length=50)),
                ('Address_line2', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=25)),
                ('Phone', models.CharField(max_length=15)),
                ('Email_id', models.EmailField(max_length=50)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='agent_photos/')),
                ('Qualification', models.CharField(choices=[('', 'Select'), ('High School', 'High School'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate')], default='', help_text="Select the user's highest qualification", max_length=30)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('Experience', models.IntegerField(help_text='Enter years of experience')),
                ('Type', models.CharField(choices=[('', 'Select'), ('Independent', 'Independent Agent'), ('Corporate', 'Corporate Agent'), ('Broker', 'Broker'), ('Tied', 'Tied Agent'), ('General', 'General Agent'), ('Specialist', 'Specialist Agent')], default='', help_text='Select status', max_length=30)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='', help_text='Current status of the agent', max_length=30)),
                ('RegDate', models.DateField(default=django.utils.timezone.now)),
                ('AllocBranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companybranches')),
                ('Login', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('distid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_district', to='company.district')),
                ('stateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_state', to='company.state')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRegistration',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email_id', models.EmailField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('qualification', models.CharField(choices=[('', 'Select'), ('High School', 'High School'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Masters', 'Masters'), ('Doctorate', 'Doctorate')], default='', help_text="Select the user's highest qualification", max_length=30, null=True)),
                ('occupation', models.CharField(max_length=20, null=True)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('physical_status', models.CharField(choices=[('', 'Select'), ('normal', 'Normal'), ('disabled', 'Disabled'), ('partially_disabled', 'Partially Disabled'), ('amputee', 'Amputee'), ('other', 'Other')], default='', help_text='Select status', max_length=30, null=True)),
                ('health_condition', models.CharField(choices=[('', 'Select'), ('healthy', 'Healthy'), ('chronic_illness', 'Chronic Illness'), ('heart_disease', 'Heart Disease'), ('diabetic', 'Diabetic'), ('cancer_history', 'History of Cancer'), ('other', 'Other')], default='', help_text='Select status', max_length=30, null=True)),
                ('business_status', models.CharField(choices=[('', 'Select'), ('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('student', 'Student')], default='', help_text='Select status', max_length=30, null=True)),
                ('identification_mark', models.CharField(max_length=30, null=True)),
                ('identity_proof', models.ImageField(blank=True, help_text='Upload Identity Proof(Aadhaar, Passport, etc)', null=True, upload_to='identity_proof/')),
                ('nominee_name', models.CharField(max_length=25, null=True)),
                ('nom_rel', models.CharField(max_length=20, null=True)),
                ('payment_mode', models.CharField(max_length=20, null=True)),
                ('credit_card_no', models.BigIntegerField(null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customer_photos/')),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('', 'Select'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='', help_text='Select status', max_length=30, null=True)),
                ('Login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('distid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_district', to='company.district')),
                ('stateid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_state', to='company.state')),
            ],
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=20)),
                ('Login', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
