# Generated by Django 5.1.5 on 2025-06-02 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_Policy',
            fields=[
                ('PolicyNo', models.AutoField(primary_key=True, serialize=False)),
                ('FinancialYear', models.IntegerField()),
                ('Total_Policies', models.IntegerField()),
                ('ModDate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
