# Generated by Django 5.1.5 on 2025-06-04 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_policy',
            name='agent_id',
        ),
    ]
