# Generated by Django 5.1.5 on 2025-06-04 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_remove_agent_policy_agent_id'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_policy',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.agentregistration'),
        ),
    ]
