# Generated by Django 5.1.5 on 2025-06-04 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_agent_policy_agent'),
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_policy',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.policies'),
        ),
    ]
