# Generated by Django 5.1.5 on 2025-06-02 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim_Status',
            fields=[
                ('CStatusCode', models.AutoField(primary_key=True, serialize=False)),
                ('CStatus', models.CharField(choices=[('', 'Select'), ('New Claim', 'New Claim'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Review', 'In Review')], default='', help_text='Select the current claim status', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBranches',
            fields=[
                ('Branch_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Company_Id', models.CharField(max_length=25, unique=True)),
                ('BranchName', models.CharField(max_length=25)),
                ('BAddress', models.CharField(max_length=50, unique=True)),
                ('emailid', models.EmailField(max_length=25, unique=True)),
                ('City', models.CharField(max_length=25)),
                ('Phone', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('distid', models.AutoField(primary_key=True, serialize=False)),
                ('distname', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_Type',
            fields=[
                ('InsType_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Ins_Type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('newsid', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=100)),
                ('news', models.CharField(max_length=500)),
                ('post_date', models.DateField()),
                ('status', models.CharField(choices=[('', 'Select'), ('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='', help_text='News Status', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('Policy_Id', models.AutoField(primary_key=True, serialize=False)),
                ('PolicyName', models.CharField(max_length=25)),
                ('PolStDate', models.DateField()),
                ('Age_at_entry', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('sum_assured', models.BigIntegerField(null=True)),
                ('policy_term', models.TextField()),
                ('PolStatus', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Policy_Benefits',
            fields=[
                ('Benefit_id', models.AutoField(primary_key=True, serialize=False)),
                ('Benefit', models.CharField(max_length=25)),
                ('Descr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Policy_Commission',
            fields=[
                ('PolComId', models.AutoField(primary_key=True, serialize=False)),
                ('Comm_For_Yrs', models.IntegerField()),
                ('Comm_Rate', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Policy_Documents',
            fields=[
                ('Docu_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Docu_Name', models.CharField(max_length=25)),
                ('Docu_File', models.FileField(blank=True, help_text='Upload policy document file (PDF, DOCX, etc.)', null=True, upload_to='policy_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Policy_Features',
            fields=[
                ('Feature_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Feature_title', models.CharField(max_length=200)),
                ('Feature_Descr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Policy_Premium',
            fields=[
                ('pol_pre_id', models.AutoField(primary_key=True, serialize=False)),
                ('pol_Premium', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Premium_Mode',
            fields=[
                ('pre_mode_id', models.AutoField(primary_key=True, serialize=False)),
                ('pre_mode', models.CharField(choices=[('', 'Select'), ('Quarterly', 'Quarterly'), ('Half-Yearly', 'Half-Yearly'), ('Yearly', 'Yearly')], default='', help_text='Select the premium payment mode', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('stateid', models.AutoField(primary_key=True, serialize=False)),
                ('stname', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sum_Assured',
            fields=[
                ('sum_assureid', models.AutoField(primary_key=True, serialize=False)),
                ('sum_assured', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('claim_id', models.AutoField(primary_key=True, serialize=False)),
                ('claim_date', models.DateField(auto_now_add=True)),
                ('purpose', models.CharField(max_length=200)),
                ('claim_amt', models.FloatField()),
                ('approval_amt', models.FloatField(null=True)),
                ('app_date', models.DateField(blank=True, null=True)),
                ('Invoice', models.FileField(help_text='Upload Hospital Bills/Pharmacy Bills/Diagnostic Reports', upload_to='invoice_documents/')),
                ('Bank_Details', models.FileField(help_text='Upload Cancelled Cheque/Passbook Front Page', upload_to='Bank_Details/')),
                ('Identity_Proof', models.FileField(help_text='Upload Aadhar card/Pan Card/Voter ID/Driving License', upload_to='ID/')),
                ('pay_status', models.CharField(choices=[('', 'Select'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='', help_text='Select the payment status', max_length=30)),
                ('cstatus_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.claim_status')),
            ],
        ),
    ]
