# Generated by Django 5.1.5 on 2025-06-02 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.customerregistration'),
        ),
        migrations.AddField(
            model_name='companybranches',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.district'),
        ),
        migrations.AddField(
            model_name='policies',
            name='insurance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.insurance_type'),
        ),
        migrations.AddField(
            model_name='claims',
            name='policy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.policies'),
        ),
        migrations.AddField(
            model_name='policy_benefits',
            name='policyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='company.policies'),
        ),
        migrations.AddField(
            model_name='policy_commission',
            name='policyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='company.policies'),
        ),
        migrations.AddField(
            model_name='policy_documents',
            name='policyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='company.policies'),
        ),
        migrations.AddField(
            model_name='policy_features',
            name='policyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='company.policies'),
        ),
        migrations.AddField(
            model_name='policy_premium',
            name='policyid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.policies'),
        ),
        migrations.AddField(
            model_name='policy_premium',
            name='premode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.premium_mode'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='company.state'),
        ),
        migrations.AddField(
            model_name='companybranches',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='company.state'),
        ),
    ]
